### ISSUE TITLE
psutil and installation

### ISSUE THREAD

**Issue by vreuter** [databio/pypiper#101]
Just flagging this as something to look out for...OSX users may experience some installation issues related to `psutil` and compilation with `clang`.

**Comment by vreuter** [comment]
I also had a little trouble installing `pypiper` in a python3.5 virtual environment running on Ubuntu 16.04. I did get  `psutil`installed and then could install `pypiper` in the environment, but brief instructions may be worth noting somewhere in the docs?

**Comment by vreuter** [comment]
Mainly suggesting this because I think this sort of thing can be frustrating on someone's first usage attempt, and it'd be nice to lower the barrier if possible and have somewhere we could easily guide someone to if they ran into difficulty.

**Comment by vreuter** [comment]
I had to `apt-get install` a package to make it work, so I think we'd need to go outside of the normal package setup/install framework to accomplish that. I think it's because this was my first time testing on my personal machine with Python3 since the psutil dependency. So it should be a solve-once sort of thing for a user rather than something that changes with each version, but I don't know if there's a reliable way to do this without supplementing the normal `setup.py` method with something else. There very well could be, though; I've just not had the use case before so don't immediately know. Agreed that'd be ideal, though.

**Comment by nsheff** [comment]
Can we add the solution to the FAQ so users who search for the error with 'pypiper' would find that?

**Comment by nsheff** [comment]
https://github.com/databio/pypiper/blob/dev/docs/faq.md
