### ISSUE TITLE
New start?

### ISSUE THREAD

**Issue by vreuter** [databio/pypiper#105]
In the code (e.g., docs for `PipelineManager`), it's noted that `new_start` is "NOT IMPLEMENTED," but it's [here in the docs](https://pypiper.readthedocs.io/en/latest/usage.html#universal-pypiper-options). Which is correct?

**Comment by nsheff** [comment]
it was not implemented, but then I implemented it and probably didn't update that second doc location... I believe it does work now.

**Comment by nsheff** [comment]
see 37ae7565dac46c9ceedff5fd835b5dee6877046a
