### ISSUE TITLE
Idea: Handling different memory units

### ISSUE THREAD

**Issue by vreuter** [databio/pypiper#106]
It looks like the `PipelineManager` assumes units of Mb for memory. We should consider supporting and/or inferring different units.

In the constructor:
```
self.mem = params['mem'] + "m"
```

**Comment by nsheff** [comment]
that expectation is coming from here:

https://github.com/databio/pypiper/blob/c248527045c8c66cfc71a53eef8ab0eac7ea2760/pypiper/utils.py#L707-L709

I would favor following the way slurm specifies it:


`--mem=<size[units]>`

Specify the real memory required per node. Default units are megabytes unless the SchedulerParameters configuration parameter includes the "default_gbytes" option for gigabytes. Different units can be specified using the suffix [K|M|G|T]. Default value is DefMemPerNode and the maximum value is MaxMemPerNode.

specifically, we assume M, but "Different units can be specified using the suffix [K|M|G|T]"
