### ISSUE TITLE
pipeline object syntax error

### ISSUE THREAD

**Issue by nsheff** [databio/pypiper#109]
```
Traceback (most recent call last):
  File "/home/ns5bc/code/dnameth_pipelines/src/rrbs.py", line 16, in <module>
    import pypiper
  File "/home/ns5bc/.local/lib/python2.7/site-packages/pypiper/__init__.py", line 6, in <module>
    from .pipeline import *
  File "/home/ns5bc/.local/lib/python2.7/site-packages/pypiper/pipeline.py", line 30
    class Pipeline(object, metaclass=abc.ABCMeta):
                                    ^
SyntaxError: invalid syntax
```

**Comment by nsheff** [comment]
just run `import pypiper` and you get this error...

@vreuter I'm getting this on Rivanna but not locally and can't figure it out...

**Comment by nsheff** [comment]
I think this may have been a cache error or something; upon purging and reinstalling it went away...

**Comment by nsheff** [comment]
well, it's back. I think it's a rivanna thing...

**Comment by vreuter** [comment]
Hm, I can't reproduce this. After pulling master and upgrading my installation, starting python and import pypiper works for me.

**Comment by vreuter** [comment]
Is it possible your import is from an older version? The source in the traceback at line 30 doesn't match the current version. It's possible that the additional argument is dynamically inserted, but that caught my eye.

**Comment by nsheff** [comment]
I think it's dynamically inserted.

**Comment by nsheff** [comment]
are you sure you're using python 2?

**Comment by michalstolarczyk** [comment]
Works both on Rivanna and on my Mac

**Comment by vreuter** [comment]
I'm not sure why it's behaving differently for different users. I had initially tested from within `code/pypiper` as you mentioned, so I checked outside of that location but it still works for me.
This is my Python2 version:
```
Python 2.7.14 |Anaconda, Inc.| (default, Dec  4 2017, 23:37:59) 
```

**Comment by nsheff** [comment]
I solved this by deleting the pipeline.py file in `.local/lib/python2.7/site-packages/pypiper`, and *then* re-installing. No idea why that wasn't getting overwritten by a re-install...
