### ISSUE TITLE
Unused parameters in function signatures

### ISSUE THREAD

**Issue by vreuter** [databio/pypiper#111]
Maybe by recent improvements, some parameters are now unused, e.g. `shell` and `errmsg` in `PipelineManager.run`. Definitely some tests would need to change, but we should work on removing these. @nsheff what are thoughts on this regarding backwards compatibility? I doubt something like `errmsg` was a hook that `PipelineManager` clients are using a lot, but what about `shell`? How soon could we fully remove it? In the meantime, could we warn of impending deprecation?

**Comment by nsheff** [comment]
I am unfamiliar with `errmsg` so it can go away as far as I'm concerned.

What makes you think that `shell` is deprecated, though? I don't think it is, but even if it was, yeah, I'm sure it's deployed...

**Comment by vreuter** [comment]
> I am unfamiliar with `errmsg` so it can go away as far as I'm concerned.
> 
> What makes you think that `shell` is deprecated, though? I don't think it is, but even if it was, yeah, I'm sure it's deployed...

That it's unused in the function

**Comment by nsheff** [comment]
Indeed. I didn't realize. Looks like @michalstolarczyk took that out here: 93aee197a3e999db15a33f888ddc67b20972b970

I think this is a problem... `shell` should still be functional... @michalstolarczyk ?

**Comment by michalstolarczyk** [comment]
As far as I remember we intended to systematically determine if shell should be used in the subprocess and at some point changed our mind, @nsheff. And then I failed to put the `shell` argument back and the `dev` branch was merged with the argument missing. 

I'll bring it back, then

**Comment by nsheff** [comment]
I think we *do* want it to be determined automatically, and it *is*... but we also want the user to be able to force it if they must... at least, that's my recollection... but I could be mis-remembering

**Comment by nsheff** [comment]
With the new system there should be very little need for a shell process anymore, right? Since you've implemented several of them, like pipes and carats?

**Comment by michalstolarczyk** [comment]
In the end only the pipes are implemented.

we didn't keep the carats (https://github.com/databio/pypiper/commit/c3dda6518171521c0da38565806ad61e4d0d87b9) as there were problems with `stderr` redirections `2>`

**Comment by nsheff** [comment]
ah, ok. well, either way, I think we should leave the ability to make `shell` explicit.

**Comment by vreuter** [comment]
Thanks @michalstolarczyk for help on this
