### ISSUE TITLE
switch documentation to using mkdocs

### ISSUE THREAD

**Issue by nsheff** [databio/pypiper#116]
Once we have python autodocs working for the mkdocs theme (https://github.com/databio/mkdocs-databio/issues/1) we should migrate these docs to the new system.

**Comment by nsheff** [comment]
I've now implemented this in a series of commits. The only thing I'm not quite happy with is the granularity of autodocs, see #129 

Along these lines, I'd like to take all the "private" PipelineManager methods and prepend an _ so they won't be documented here...

http://code.databio.org/pypiper/autodoc_build/pypiper/

for example, `atexit_register`, `complete`, `completed`, `failed`, `flag_file_path` -- these are internal and not intended for a developer, right?

**Comment by vreuter** [comment]
Yeah that seems right.

**Comment by vreuter** [comment]
@nsheff the members you call out above are now protected, save for `complete`, which is used by `Pipeline`

**Comment by nsheff** [comment]
ok great -- I think there are lots of others that warrant protecting though, don't you? I was just listing some examples... others I would protect include, has_exit_status is_running set_status_flag fail_pipeline
do you think those stay?

**Comment by vreuter** [comment]
No, I just figured you were listing each that you wanted hidden; I'll protect the others also.

**Comment by nsheff** [comment]
Ok this is done. thanks
