### ISSUE TITLE
Need special handling for protected object members

### ISSUE THREAD

**Issue by vreuter** [databio/pypiper#117]
`PipelineManager` here echoes a requested attribute if the name doesn't map to a value (`default=True`) in the call to the `AttributeDict` constructor. This can cause a problem, at least in (some?) Python 2.7 versions. For example:
```
...
    spikein_epiconf = copy.deepcopy(param.epilog)
  File "/home/vpr9v/.conda/envs/py2/lib/python2.7/copy.py", line 174, in deepcopy
    y = copier(memo)
TypeError: 'str' object is not callable
Pipeline status: running

### Pipeline failed at:  (01-30 16:12:31) elapsed: 0.0 _TIME_
...
```

This issue is really just a hypothesis, but I think that what's likely happening is that the lookup of `__deepcopy__` is returning a `str` rather than a `callable` or `None`. See the [`copy` module source](https://github.com/python/cpython/blob/2.7/Lib/copy.py#L145-L194)

`AttributeDict` should never echo attributes with the flanking double underscores, as is the case in `peppy`. This will be addressed by using an independent type as in https://github.com/pepkit/mado/.

**Comment by nsheff** [comment]
should we just eliminate that 'default' capability? it might be more trouble than it's worth...
