### ISSUE TITLE
Idea: target existence tweak

### ISSUE THREAD

**Issue by vreuter** [databio/pypiper#120]
We can forcibly overwrite a target that exists, but what about introducing a parameter to overwrite a target only if it's empty? As with no output at all, I feel like it's pretty common for some processing error to result in an empty output, which I'd like to attempt to replace on a retry attempt.

**Comment by nsheff** [comment]
What's the use case? you are suggesting a new setting that would overwrite targets, but only if they are empty. I am having trouble thinking of when I would want to do that, versus either always overwrite or never overwrite. it seems like it would be highly dependent on the underlying tools, which seems to introduce a complication but I don't really see utility yet...

**Comment by vreuter** [comment]
I don't have a use case in mind; this came up after often seeing users write in with errors related to empty outputs from other GitHub projects that I follow. Other than a file functioning strictly as a flag to indicate completion of something, I don't see a reason that a target should be empty, and that's a case that the pipeline author, who would also be the one introducing the possibility to overwrite an empty target, would know about.

**Comment by nsheff** [comment]
I think I'm missing something then; the user of this feature would be a pipeline user, not a pipeline developer, right?

in our pipelines we frequently use empty flag files as targets.

what about introducing a warning message about empty targets?

**Comment by vreuter** [comment]
The person specifying whether the option is active would be the pipeline user, but the pipeline developer would have control over the subset of `run` commands within the pipeline for which the option would have any meaning (i.e., a `run` command could be set up in a pipeline such that it would behave the same regardless, or it could "listen" for the option's value)

**Comment by nsheff** [comment]
I see -- so that's a bit different from the current target overrides, where the user turns them on with the `--new-start` mode.

SO this would be a new pipeline mode that operates as `new-start`, but only for *certain* commands, and only if those commands have *empty* targets. Am I understanding?

**Comment by vreuter** [comment]
Yeah, I think so. I'm interpreting what "*certain* commands" as "*certain* run commands," which is what I was meaning. I wasn't thinking of "listening" for that option in any command other than `run`

**Comment by nsheff** [comment]
I think I don't see the utility in this suggestion at this point. I can't see it improving any of my existing pipelines at least so the complexity and effort doesn't seem to have any payout...  But if you want to use it, or have a use case where it would be helpful, feel free to reopen/implement.
