### ISSUE TITLE
Proportion reporting

### ISSUE THREAD

**Issue by vreuter** [databio/pypiper#124]
Why report proportions (like calculated by some `ngstk` functions) as percentages?

**Comment by nsheff** [comment]
what is the alternative? reporting them as a proportion, something like `1829492/1924459`?

**Comment by vreuter** [comment]
No, just the decimal, so not multiplying by 100.

**Comment by nsheff** [comment]
I see. either would be acceptable... it's more visually appealing to go to percentages I think:
`75.8842` vs `.758842`
we usually think of these things in terms of percents... alignment rate is 78% or 64%... it's just the conventional way of thinking (in my subset of the community)

**Comment by vreuter** [comment]
Yeah I guess it's probably pretty mixed. I think there may be reason to favor the raw form if it was _not_ the case that each use case truly is a _rate_ that should be in [0%, 100%], but it looks like that _is_ the case, so totally makes sense.

**Comment by nsheff** [comment]
I think for things that aren't actually out of 100, I wouldn't report them as percents...
