### ISSUE TITLE
pypi logo

### ISSUE THREAD

**Issue by nsheff** [databio/pypiper#126]
for the next release, should look into this; the logo isn't rendering at pypi:

https://pypi.org/project/piper/

**Comment by vreuter** [comment]
Agree, this is on my radar. PyPI and I needed to take a break after a couple days of...tense...interaction, though :wink:

**Comment by nsheff** [comment]
I'm actually not sure this is easy to do, realized none of my packages do this...

**Comment by vreuter** [comment]
@nsheff can i have upload perms on test PyPI?

**Comment by nsheff** [comment]
granted

**Comment by vreuter** [comment]
Thanks!

**Comment by vreuter** [comment]
https://github.com/databio/pypiper/commit/6551468060c5c863ca59bb6ab5cced6edf117ebe
