### ISSUE TITLE
adapt docstrings for lucidoc processing

### ISSUE THREAD

**Issue by nsheff** [databio/pypiper#129]
Not sure if it's easier to adapt lucidoc to handle the pypiper docstrings, or change the pypiper docstrings to match lucidoc... @vreuter do you have a preference here?

**Comment by vreuter** [comment]
It’s easier to change the docstrings, which I’m happy to do if you want. I’d like lucidoc to support numpy and (maybe) google styles at some point but for the Sphinx/RST style I’d like to keep it at inline only. Other than working with Sphinx, I think a win for the Sphinx/RST style is line number brevity, which is sacrificed with the separate lines for types

**Comment by nsheff** [comment]
> It’s easier to change the docstrings, which I’m happy to do if you want.

That sounds great! if you have a moment.

>  I think a win for the Sphinx/RST style is line number brevity, 

Ok, agreed
