### ISSUE TITLE
get_proc_name confusion

### ISSUE THREAD

**Issue by nsheff** [databio/pypiper#136]
```
def get_proc_name(cmd):
    """
    Get the representative process name from complex command

    :param list cmd: a string to be processed
    :return str: the command
    """
    return "".join(cmd).split()[0].replace('(', '').replace(')', '')
```

returns: 

```
In [7]: get_proc_name(["bowtie2", "--blah"])
Out[7]: 'bowtie2",--blah'
```

Shouldn't that be a space? 

```
  return " ".join(cmd).split()[0].replace('(', '').replace(')', '')

```

returns:
bowtie2

Also why does it have the type as 'list' and then says "a string to be processed" ?

**Comment by michalstolarczyk** [comment]
the param type is wrong, it should be a `str`

**Comment by nsheff** [comment]
then why does it say `"".join()` ?

**Comment by michalstolarczyk** [comment]
hmm that has to be part of the previous way the command name was determined and it did not work properly, so I changed it. 

We can take the `join` out, I guess

**Comment by nsheff** [comment]
But I am using it for a list and then the join is necessary. It was probably expecting a list.

**Comment by michalstolarczyk** [comment]
https://github.com/databio/pypiper/blob/f15e873e54ff03a6c86098371ec01356518f2e92/pypiper/manager.py#L795

That's how it used to be. I've just added the parentheses removal, since the process name included some when the beginning of the command included one
And you're right, it expected a list, my bad

**Comment by nsheff** [comment]
this works for me

```
def get_proc_name(cmd):
    """
    Get the representative process name from complex command

    :param Union[str, list] cmd: a command to be processed
    :return str: the command
    """
    if isinstance(cmd, list):
        cmd = " ".join(cmd)

    return cmd.split()[0].replace('(', '').replace(')', '')
```

vince how should we document dual types in the docstring?

**Comment by vreuter** [comment]
Cool, good deal. It'd be `:param str | list[str]`
