### ISSUE TITLE
cleanups appear to be failing

### ISSUE THREAD

**Issue by nsheff** [databio/pypiper#143]
PEPATAC puts stuff in clean_add, but it's not being cleaned.

**Comment by vreuter** [comment]
Is this also at the root of the unzipped FASTQs and the methylation pipelines?

**Comment by vreuter** [comment]
> May this also be at the root of the unzipped FASTQs and the methylation pipelines?

Ah OK just checked email :man_facepalming:

**Comment by nsheff** [comment]
actually I think I'm wrong and it appears the cleanups are working after all... maybe they weren't working in 0.10 or something. I'm trying to figure out what's going on.

**Comment by nsheff** [comment]
the real issue is: in `dirty` mode, the `clean_add` function is now ignored for some reason.

```
pm = PipelineManager(name="interactive", outfolder=os.path.expanduser("~"), dirty=True)
pm.clean_add("test.txt")
pm.cleanup_list
pm.cleanup_list_conditional
pm.stop_pipeline()
```


```
In [19]: pm.cleanup_list                                         
Out[19]: []

In [20]: pm.cleanup_list_conditional                             
Out[20]: []
```

**Comment by vreuter** [comment]
Does "test.txt" exist? `clean_add` treats the expression for what to add as a pattern for `glob`, so if no path matches the pattern, nothing is added. Not sure if that's the intended behavior, just noting what happens. There's some additional messaging on `dev` now to this effect.

**Comment by nsheff** [comment]
yeah, I figured that out, and it also is not adding to that list at all but just writing directly to the file. So this isn't the problem, it's somewhere else.

**Comment by vreuter** [comment]
Well I mean, `dirty` --> `manual` = `True`, so the `cleanup_list` and `cleanup_list_conditional` append checks are never executed if `dirty` is `True`:
https://github.com/databio/pypiper/blob/dev/pypiper/manager.py#L1821-L1823
https://github.com/databio/pypiper/blob/dev/pypiper/manager.py#L1833-L1858

I guess I don't know the intended behavior(s)--among the following subset--for the "test.txt" example you presented :
- [ ] update `cleanup_list_conditional`
- [ ] update `clean_list`
- [ ] perform file write

**Comment by nsheff** [comment]
I'm still investigating... I'll let you know, don't worry about it for now

**Comment by nsheff** [comment]
looks like the files are getting correctly added to the cleanup script, but it's somehow getting re-initialized or something, so they are disappearing from int...

**Comment by nsheff** [comment]
I believe I figured this out. Apparently, the `clean_add` function in `dirty` mode is expecting the pipeline to be run *from the output directory*. So when we [made cleanups relative](https://github.com/databio/pypiper/issues/63), I must have missed this. As a result, when a pipeline is *not* run from the output directory these cleanups are not being found and are thus not being added to the cleanup script.

I'm working on a solution.
