### ISSUE TITLE
follow functions and process ID determination in pipeline rerunning

### ISSUE THREAD

**Issue by michalstolarczyk** [databio/pypiper#151]
related to: #142, #144

when a follow function uses `run` method (like `ngstk.check_trim`), then it is counted as a process (process ID is incremented) since it uses `callprint` method BTS. Conversely, follow functions that do not use the `run` method are not counted as processes (process ID is _not_ incremented). 

Is there a way to distinguish between these in command skipping/counting process after restarting the pipeline?

[Currently](https://github.com/databio/pypiper/commit/3335c8bb5181ae4f4c2202ad8f5ac0966f9a2076) both are treated the same way, **which is wrong** -- the process IDs in a rerun pipeline do not match the previous ones because the process IDs are incremented for every single follow function, but sometimes they should _not_ be

**Comment by nsheff** [comment]
can we make it so that any command run as a follow function *does not* increment the counter? It could be assigned the id of the original command plus "f". this way follow functions in the original run would not increment the counter.
