### ISSUE TITLE
Are there any better tutorials that what is present on the pypiper website?

### ISSUE THREAD

**Issue by Lamm-a** [databio/pypiper#168]
Whilst there is a tutorial for pipeline making on the pypiper website it level of comments are very generalised making it almost impossible to learn from as a beginer.  An example being how to actually construct a command, it just shows you one without detailing how to construst it, such as how to indicate flags for prodigal run or something. Correct me if I am missing something here :)

As a result I am trying to look elsewhere for a more comprehensive tutorial but am unable to find one. Any advice?

**Comment by nsheff** [comment]
Hi @Lamm-a -- 

Thanks for your feedback. The only tutorials I've put together are the [simple one](http://pypiper.databio.org/en/latest/hello-world/) and the [more advanced one](http://pypiper.databio.org/en/latest/basic-pipeline/)...

I don't quite understand what you mean about constructing a commands. Commands are simply shell commands... they are exactly what you would have run in your bash script. Can you explain what you mean by "how to indicate flags for prodigal run or something"? I am happy to help -- can explain clearly what is confusing you?

**Comment by Lamm-a** [comment]
Hi @nsheff,

Apologies for the poor explination. I am getting confused by the syntax of how to call the shel commands for a given programme. I am trying to make a biosynthetic gene cluster detection pipeline but depending on the input may been to run some programmes upstream, such as merging paired end reads and annotation. 

I am unsure how to, say for the BCG detector AntiSMASH, mimic this command in the pipeline:

`antismash --knownclusterblast --subslusterblast --full-hmmer  --smcog --outputfolder /path/to/output-location/  path/to/input-files/$file`

especially where $file will change for each file in the directory (I assume I need to use Looper here maybe)?

**Comment by nsheff** [comment]
Pypiper just needs to know the command for one sample. You would do something like:

```
pm.run("antismash --knownclusterblast --subslusterblast --full-hmmer --smcog --outputfolder /path/to/output-location/ path/to/input-files/file.txt")
```

All you have to do is construct that command using python. So, your question is not a pypiper question, it's a python question. If you're unfamiliar with python, then pypiper might not be the right framework for you. If you want to use it, I'd suggest taking a few python tutorials. You just need to learn how to do basic string manipulation to construct that string, then pass it to `pm.run()` exactly like you would run it on the shell.

**Comment by nsheff** [comment]
@Lamm-a  were you able to get this figured out?
