### ISSUE TITLE
Consider removing -R?

### ISSUE THREAD

**Issue by vreuter** [databio/pypiper#173]
Maybe I'm using it wrong, but when writing a `pypiper` pipeline with an option `-R` and using `add_pypiper_args`, I hit a snag:
```
argparse.ArgumentError: argument -R/--recover: conflicting option string: -R
```
`--recover`'s a great option, but I feel like having a pipeline with its own `-R` may not be terribly uncommon. `--recover` seems much less likely to cause collision, though. Could it be only `-R`?

**Comment by nsheff** [comment]
Yeah.... We made all the built-in args use capital letters to distinguish them. I guess this point applies to all pypiper args.

https://github.com/databio/pypiper/blob/67908f2ee5f51fa5fdddb67eb6d7891aefeeda6a/pypiper/utils.py#L884-L939

My protocol has always been to use lowercase letters for the pipeline-specific args since pypiper args are all uppercase. But maybe we should consider another general way to do this? Like pass pypiper args in a different way so there's no possibility of conflict?

**Comment by vreuter** [comment]
Ah yeah I guess I tend to define all my single-letter options as capital. Good point, this is a more general problem. Don't know off top of head...would sequence of operations matter? If effort's put into this, I think it should be that order is irrelevant. That is, behavior should be the same regardless of the sequence of `add_pypiper_args` vs. individual `add_argument` calls. If there are any collisions among the "pool" of argument names being defined, they should all be handled equally (IMO). This may already be the case, just brainstorming here.

I think `add_pypiper_args` should actively check for conflicting options. Obviously this doesn't help for any `add_argument` call executed after the `add_pypiper_args` (guess that'd need a patched/subclassed `ArgumentParser`?), but it would at least make it the case that if `add_pypiper_args` were called at the end of the CLI definition (after all `add_argument`s), the failure could be more specifically pinned down in the messaging (e.g., for a new `pypiper` user, or someone using a pipeline without knowledge of `pypiper`).

**Comment by vreuter** [comment]
I think maybe this isn't wort pursuing. I think most pipeline developers (i.e., someone who'd be using `add_pypiper_args`) would be able to figure out what's going on. And it seems my convention of uppercase for the single-letter isn't the norm. I'm closing but feel free to reopen if you disagree and think it's worth more active checking and better messaging.

**Comment by nsheff** [comment]
Well, It *is* annoying that this effectively means pypiper can't be used for any pipeline that wants any of those option names.  I actually am kind of fond of the idea of passing pypiper args in a separate way somehow. 

I think your suggestion is good, but even better would be a different way to influence pypiper. Like, `--pypiper RTND` or something. It's a string with codes, which are parsed separately as options. But it's less easy for options with values.

I just don't see the best way to do this, but I think your'e right that the current way is not ideal...
