### ISSUE TITLE
pypiper args not being picked up

### ISSUE THREAD

**Issue by vreuter** [databio/pypiper#176]
Things like `--new-start` and `--recover` aren't getting picked up for me. I'm using the release versions of `looper` and `piper`...not sure if I'm incorrectly using or if something's amiss. Here's a sample command:
```
looper run $CODE/path/to/project/config --dry-run --recover --new-start
```
And here's where I add the args in my parser, and then where I create the manager:
```
def _parse_cmdl(cmdl):
    ...
    parser = pypiper.add_pypiper_args(parser)
    ...
    return parser.parse_args(cmdl)
...
...
def main(cmdl):
    opts = _parse_cmdl(cmdl)
    pm = pypiper.PipelineManager(
        name = "mypipe", outfolder = sample_folder, args = opts,
        config_file = pipe_config_file, logger_kwargs = {"level": "DEBUG"})
```

**Comment by nsheff** [comment]
At some point the looper API was changed to pass commands in through the `--command-extra`  (`-x` for short) argument. Now, any commands passed directly to looper, like you're doing above with `--dry-run`, are assumed to be passed to looper. If you want to pass a command to the pipeline, you'd do something like `looper run ... -x "--command-for-pipeline"`.

This disambiguates commands intended to be consumed by looper, vs those intended to be passed along to the pipeline.
