### ISSUE TITLE
Python 3 changes the type of filter() from a list like object to an iterator.

### ISSUE THREAD

**Issue by jpsmith5** [databio/pypiper#179]
https://github.com/databio/pypiper/blob/8f9993ab593021be022727cef60e150a764c0ac1/pypiper/ngstk.py#L304

Must explicitly convert the return from filter to a list.
Fix:
```
n_input_files = len(list(filter(bool, input_args)))
```

Also at: https://github.com/databio/pypiper/blob/8f9993ab593021be022727cef60e150a764c0ac1/pypiper/ngstk.py#L521-L522

**Comment by nsheff** [comment]
Ok, the fix in 0.12.3 has be released to pypi. Can you confirm that this solves your issues?
