### ISSUE TITLE
SyntaxWarning on first import

### ISSUE THREAD

**Issue by vreuter** [databio/pypiper#196]
Upon first import of pypiper (version 0.12.3) in a Python 3.10 REPL, I see a few syntax warnings based on `is`-based, rather than `==`-based, comparison. Could code be changed to avoid that?
```python
pypiper/utils.py:349: SyntaxWarning: "is" with a literal. Did you mean "=="
```

**Comment by donaldcampbelljr** [comment]
I believe this is now fixed with 0b430c7ab416f35389a85683c56c2258adb31e60
