### ISSUE TITLE
failures of early stages in shell pipelines don't fail the pipeline

### ISSUE THREAD

**Issue by nsheff** [databio/pypiper#22]
If you run a shell command through Pypiper using a shell pipe (`|`), then the shell will return the return value of the last command in the pipe string. Thus, even if an early step fails, it could return a 0, and the pypiper pipeline would continue.

You can solve this in `bash` with an option called `pipefail`, which makes it so failure at any stage fails the whole pipe. If you ask me, this should have been the default.

Anway, if you force the python subshell to use bash, you can do this in python like explained [here](http://stackoverflow.com/questions/21742587/equivalent-of-set-o-pipefail-in-python). But maybe there's a better way?

**Comment by afrendeiro** [comment]
Well spotted! I will look into it.

**Comment by nsheff** [comment]
@michalstolarczyk Where do we stand on this pending feature release? Are you ready to have it tested by others at this point?
