### ISSUE TITLE
Support use of virtual environments?

### ISSUE THREAD

**Issue by vreuter** [databio/pypiper#25]
It seems that right now `PipelineManager.run` will not find packages installed in a virtual environment. This may depend on the argument to the `shell` parameter. It may also/instead be that some hook mechanism needs to be added to make this possible. This is desirable for users wishing to keep relatively clean their system site-packages.

**Comment by nsheff** [comment]
@vreuter can you recall/clarify what is the problem here?

**Comment by nsheff** [comment]
@vreuter just cleaning up old issues, can you clarify/close this issue?

**Comment by vreuter** [comment]
I haven't in quite some time had a a problem that's seemed to stem from this, so I'll close it.
