### ISSUE TITLE
File waiting method is protected

### ISSUE THREAD

**Issue by vreuter** [databio/pypiper#48]
`PipelineManager._wait_for_file` is protected. This seems like a useful public method for the `PipelineManager` API, and it's used in e.g. `open_pipelines/pipelines/chipseq.py`. If there's not an public wrapper around this, could this be made public?

**Comment by afrendeiro** [comment]
Yeah, I noticed this too and I think it does make sense to be public. In fact in an earlier version it was indeed.

**Comment by nsheff** [comment]
I've been thinking about this.

Background: That function is not used anywhere within pypiper. It's only used (apparently) in this pipeline (or maybe some others). 

My thoughts: I actually think it sort of breaks the mantra of pypiper to have it called externally. I think pypiper should manage the waiting, entirely via `run`. If something outside is trying to mess with waiting, that indicates that something complex and confusing is going on in the pipeline, which isn't in line with pypiper's goal. In this case, it indicates that this pipeline is trying to implement external dependencies, which I think is not the right way to solve the problem. There are other, better ways to solve it that are more straightforward and fitting with the goals of the tools.

So I would be in favor of leaving it there, but protected, exactly to indicate that you *can* do this, but you *shouldn't*.

**Comment by vreuter** [comment]
So you're saying that changes would be made within `pypiper`, in which `run` and/or other methods or functions would call `_wait_for_file` to get the desired effect? In that case, I'm totally fine with leaving it protected and routing usage through public routes. I don't think, though, that it should be left in protected status and not used anywhere.

I don't know how the convention is intended, but I don't view the loose protective mechanism as a language strength, rather a weak attempt to simulate truly private methods. Under that premise, it doesn't make to have a protected method or function that isn't used in its narrowest scope, so I'd only favor leaving it as-is if we make changes to other `PipelineManager` method(s) that then use it.

**Comment by vreuter** [comment]
OK I'll leave this open but am also fine if it's closed then; the larger goal can be discussed [here](https://github.com/epigen/pypiper/issues/49)

**Comment by nsheff** [comment]
Sounds good. Closing this issue in favor of #49.
