### ISSUE TITLE
Include PipelineInterface outputs in sample YAML

### ISSUE THREAD

**Issue by vreuter** [databio/pypiper#57]
See https://github.com/epigen/looper/issues/170, specifically https://github.com/epigen/looper/issues/170#issuecomment-338017933

**Comment by nsheff** [comment]
OK, so the idea here is that pypiper should produce a `yaml` representation of the completed sample at the end of the pipeline (or, I suppose, an incomplete one at pipeline failure)

**Comment by afrendeiro** [comment]
I think this makes a lot of sense.
Just one question: will pypiper modify the existing yaml file created at submission or make a new one for example in the sample output directory?

**Comment by nsheff** [comment]
I think a new one in the sample output directory makes the most sense.

**Comment by vreuter** [comment]
https://github.com/pepkit/peppy/issues/170 leads with mention of conceptual and on-disk distinction between submission and postprocessing analysis data. What are thoughts about that? Is it worth separating them to have a more readable/intelligible "analysis" YAML, and a separate, likely less easily readable submission one? This seems feasible to implement (with something like a set difference between YAML/dict representation of the `Sample` at time of pipeline start, and that same representation at time of pipeline completion, perhaps including KV pairs with a changed value as well in the "analysis" output), but not sure if that has some value or not?

**Comment by nsheff** [comment]
I still don't see value in taking things out of the final sample yaml.

**Comment by vreuter** [comment]
You’ve previously said things in the spirit of, “Sample YAMLs have a lot of stuff in them.” The value would be to declutter.

**Comment by nsheff** [comment]
Ok yes I do see that value. but I think it will be more useful to have all that info in one place... I guess that's my current feeling. maybe can change my mind.

maybe the final yaml doesn't need the entire project representation, though.

**Comment by vreuter** [comment]
Well if anything other than the sample-independent metadata is in there now from the project reference then that’s a bug; it should already be excluded given the prohibition of a fully Project being stored in the prj ref in the sample

**Comment by nsheff** [comment]
perfect.

**Comment by vreuter** [comment]
@nsheff how do you propose proving `pyiper` with a `Sample` instance? I think @afrendeiro often writes pipelines in a style amenable to this ticket, but that most `databio` pipelines aren't written that way.

**Comment by nsheff** [comment]
your comment has me thinking about it...the pipeline interface yaml may preclude the need for this, because you could get all this information from the PEP + pipeline interface.

in other words, if the `outputs` section of the pipeline interface is populated, then looper+peppy could create the *final* sample yaml, without even any information from the pipeline. it's all in the interface.

**Comment by vreuter** [comment]
> your comment has me thinking about it...the pipeline interface yaml may preclude the need for this, because you could get all this information from the PEP + pipeline interface.
> 
> in other words, if the `outputs` section of the pipeline interface is populated, then looper+peppy could create the _final_ sample yaml, without even any information from the pipeline. it's all in the interface.

Yeah, I was trying to leave comment as open as possible to not bias suggestions, but that's similar to what I was thinking. A problem is how to handle existence. Do we want to include any logic for checking and communicating existence of the intended outputs? That seems nice, but also there's no way for `looper` to know when the submission (or a substage that generates a specific output) is complete and therefore when it's appropriate to check existence.

_So_, I think we could do...
- Nothing -- just attach the outputs to the secondary/post-pipeline/analysis YAML, and defer to consumers of that file to contend with existence or not of missing  outputs
- Introduce a new `looper` subcommand/program that could be run after-the-fact and produce all such YAML files, rebuilding the samples as done initially, populating the output paths based on the attributes of each `Sample` instance, then checking the paths. The final output could omit missing outputs, or we could include all of them and annotation which ones do or don't exist.

**Comment by nsheff** [comment]
thought: does there even need to be a second yaml? The first yaml could just have outputs in it... if there is a secondary yaml, when/where would it be produced? I don't really like the new looper command idea because it's adds another step. I do see the benefit of checking though.

**Comment by vreuter** [comment]
https://github.com/pepkit/looper/issues/201
