### ISSUE TITLE
Proposal: eliminate dependence on particular nesting of pipeline manager settings

### ISSUE THREAD

**Issue by vreuter** [databio/pypiper#61]
Right now, the access pattern for, e.g., the path to the sequencing adapters is `pm.config.resources.adapters`. It would be nice to have this and related details of a pipeline manager's configuration settings directly available, e.g. `pm.adapters`. Not only would this simplify usage within pipelines, but also allow the code to flex around changes in pipeline interface files. Then changes to how the interface file is parsed would only impact pipeline interface files. A pipeline author using `pypiper` would need only to update interface file(s), not associated pipeline(s).

**Comment by nsheff** [comment]
the `resources` component is pipeline-author-specific, so we can't do anything about that.
getting rid of the `.config` step we could do, though. I usually just do this with:
```
config = pm.config
resources = config.resources
```
Then I just call `resources.adapters`
```
But that's up to the pipeline author.

I guess I'm just saying, this is not somethign that can be universally solved at the pypiper level, since pipeline authors can put whatever they want in the pipeline config yaml.

**Comment by vreuter** [comment]
That an author can put what he or she wants in the interface doesn't preclude `pypiper` from looking for particular sections, parsing them in a particular way, and updating the pipeline manager accordingly. That system seems fairly analogous to a `looper` project config...

**Comment by nsheff** [comment]
Sure, but then that would need to be a documented standard, I would think.

**Comment by nsheff** [comment]
Hey @vreuter do you have any additional thoughts about this, now quite some time later?

**Comment by vreuter** [comment]
I basically agree with your thought (it sounds like) that the access pattern is more up to the pipeline author, partially for the somewhat unusual nature of the object in question. I'm a bit more used to scenarios in which the user is not really structuring the object being used, and knows only about a surface API layer. In this case, though, since a user (of `pypiper) (the pipeline author) can not only be very aware of the hierarchical structure, but also can modify it, I think that providing this sort of access propagation introduces complexity without much extra benefit. In fact, in a way it would cross-contaminate otherwise disjoint namespace layers. Someone may have the same key mean different things at different nesting levels.
