### ISSUE TITLE
Consider reporting some null form for max memory for short-running processes

### ISSUE THREAD

**Issue by vreuter** [databio/pypiper#95]
Why is peak pipeline memory usage sometimes listed as negative?
```
Process 102058 returned: (0). Elapsed: 0:00:00. Peak memory: (Process: -1.0GB; Pipeline: 0.275GB)
```

**Comment by nsheff** [comment]
Are you using the `dev` branch? It is what happens when process takes less than .0001 seconds to complete, and python never has time to check memory (right @michalstolarczyk?)...

We should probably report "None" or "N/A" instead of `-1` though. I think that's what `psutil` reports.

**Comment by vreuter** [comment]
:ok_hand: good to know. No big deal, I was just curious but will update this accordingly.

**Comment by michalstolarczyk** [comment]
Thats right @nsheff. It looks like there are still some that end this quickly..

**Comment by nsheff** [comment]
@michalstolarczyk can you switch to reporting None or NA or something other than -1?
