### ISSUE TITLE
pre tags are not used for some processes

### ISSUE THREAD

**Issue by nsheff** [databio/pypiper#97]
I have a process here that doesn't enclose its output in `<pre></pre>`:

```
### Methylation calling (testxmz) Spike-in:  (11-05 19:48:51) elapsed: 1.0 _TIME_

[E::hts_open_format] Failed to open file /sfs/lustre/allocations/shefflab/processed/aml_e3999/results_pipeline/13424/bismark_spikei
n/13424.spikein.aln.deduplicated.sorted.bam
samtools view: failed to open "/sfs/lustre/allocations/shefflab/processed/aml_e3999/results_pipeline/13424/bismark_spikein/13424.sp
ikein.aln.deduplicated.sorted.bam" for reading: No such file or directory
```

**Comment by nsheff** [comment]
should this be fixed in the latest commits? I will try them.

**Comment by nsheff** [comment]
I can confirm this issue still exists in the latest commits on `dev`. maybe something to do with handling redirects or pipes? this particular command uses `>>` -- I thought we weren't doing anything with that?

**Comment by michalstolarczyk** [comment]
Yes it was supposed to be fixed with the latest changes. I’m gonna look into that this today.

**Comment by nsheff** [comment]
Ok then I'll close. I'll reopen if I find it again.
